/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class BuildingSchema extends BaseModel {
  static $columns = ['cleanlinessScore', 'code', 'createdAt', 'description', 'id', 'isActive', 'name', 'supervisorId', 'updatedAt'] as const
  $columns = BuildingSchema.$columns
  @column()
  declare cleanlinessScore: string | null
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean | null
  @column()
  declare name: string
  @column()
  declare supervisorId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ComplaintCategorySchema extends BaseModel {
  static $columns = ['createdAt', 'defaultPriority', 'description', 'id', 'name', 'updatedAt'] as const
  $columns = ComplaintCategorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare defaultPriority: number
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ComplaintVoteSchema extends BaseModel {
  static $columns = ['complaintId', 'createdAt', 'id', 'updatedAt', 'userId'] as const
  $columns = ComplaintVoteSchema.$columns
  @column()
  declare complaintId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class ComplaintSchema extends BaseModel {
  static $columns = ['id', 'complaintCode', 'zoneId', 'floorId', 'buildingId', 'reportedBy', 'isAnonymous', 'categoryId', 'description', 'photoUrl', 'status', 'priority', 'assignedSupervisorId', 'escalationLevel', 'reportedAt', 'assignedAt', 'inProgressAt', 'resolvedAt', 'resolutionTimeMinutes', 'resolutionPhotoUrl', 'resolutionRemark', 'createdAt', 'updatedAt'] as const
  $columns = ComplaintSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare complaintCode: string
  @column()
  declare zoneId: number
  @column()
  declare floorId: number
  @column()
  declare buildingId: number
  @column()
  declare reportedBy: number | null
  @column()
  declare isAnonymous: boolean | null
  @column()
  declare categoryId: number
  @column()
  declare description: string | null
  @column()
  declare photoUrl: string | null
  @column()
  declare status: string | null
  @column()
  declare priority: string
  @column()
  declare assignedSupervisorId: number | null
  @column()
  declare escalationLevel: number | null
  @column.dateTime()
  declare reportedAt: DateTime
  @column.dateTime()
  declare assignedAt: DateTime | null
  @column.dateTime()
  declare inProgressAt: DateTime | null
  @column.dateTime()
  declare resolvedAt: DateTime | null
  @column()
  declare resolutionTimeMinutes: number | null
  @column()
  declare resolutionPhotoUrl: string | null
  @column()
  declare resolutionRemark: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class FloorSchema extends BaseModel {
  static $columns = ['id', 'buildingId', 'floorNumber', 'name', 'createdAt', 'updatedAt'] as const
  $columns = FloorSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare buildingId: number
  @column()
  declare floorNumber: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class JobCardSchema extends BaseModel {
  static $columns = ['id', 'complaintId', 'zoneId', 'supervisorId', 'type', 'status', 'scheduledFor', 'completedAt', 'proofPhotoUrl', 'remark', 'createdAt', 'updatedAt'] as const
  $columns = JobCardSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare complaintId: number | null
  @column()
  declare zoneId: number
  @column()
  declare supervisorId: number
  @column()
  declare type: string
  @column()
  declare status: string | null
  @column.dateTime()
  declare scheduledFor: DateTime | null
  @column.dateTime()
  declare completedAt: DateTime | null
  @column()
  declare proofPhotoUrl: string | null
  @column()
  declare remark: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RoleSchema extends BaseModel {
  static $columns = ['id', 'name', 'description', 'createdAt', 'updatedAt'] as const
  $columns = RoleSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare description: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['id', 'name', 'email', 'password', 'roleId', 'phone', 'isActive', 'emailVerifiedAt', 'createdAt', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare email: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare roleId: number
  @column()
  declare phone: string | null
  @column()
  declare isActive: boolean | null
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ZoneTypeSchema extends BaseModel {
  static $columns = ['id', 'name', 'description', 'createdAt', 'updatedAt'] as const
  $columns = ZoneTypeSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare description: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ZoneSchema extends BaseModel {
  static $columns = ['id', 'floorId', 'buildingId', 'zoneTypeId', 'name', 'qrCode', 'cleaningFrequencyHours', 'cleanlinessScore', 'lastCleanedAt', 'createdAt', 'updatedAt'] as const
  $columns = ZoneSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare floorId: number
  @column()
  declare buildingId: number
  @column()
  declare zoneTypeId: number
  @column()
  declare name: string
  @column()
  declare qrCode: string | null
  @column()
  declare cleaningFrequencyHours: number | null
  @column()
  declare cleanlinessScore: string | null
  @column.dateTime()
  declare lastCleanedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
